### PR TITLE
Update UnitExtensions.cs

### PR DESCRIPTION
**Pull request by NightMoon032**
fix nullreference ex

### CODE REVIEW

**Comment by PixlTec** [comment]
This code is the same as the above. Why have you requested this change?

**Comment by NightMoon032** [comment]
https://cdn.discordapp.com/attachments/332311270873104384/342280234265083904/unknown.png

https://github.com/NightMoon032/AimTec/blob/master/Flowers%20Ryze/MyCommon/MySpellManager.cs#L31

EX: when you dont have Ignite, it will have a error

**Comment by andreluis034** [comment]
The reference null exception isn't in the code you commited, it's on some function FirstOrDefault uses.
The code you edited is exactly the same as before

**Comment by NightMoon032** [comment]
OCD

**Comment by PixlTec** [comment]
Fixed.

**Pull request closed without merging**
